import type { GameAsset, JobSummary, ProjectSummary, WorkbenchPayload } from "./types";

const portrait = (person: string, pose: string) =>
  `/demo-assets/portraits/${person}/${pose}.webp`;

const qa = (resolution: string, size: string) => [
  { id: "resolution", label: "分辨率符合规格", result: resolution, passed: true },
  { id: "subject", label: "主体完整，无裁切", result: "通过", passed: true },
  { id: "format", label: "格式与文件大小符合规范", result: `WebP · ${size}`, passed: true },
  { id: "alpha", label: "透明边缘与残色检查", result: "通过", passed: true },
];

export const demoProject: ProjectSummary = {
  id: "emperor-simulator",
  name: "皇帝模拟器",
  path: "/Users/0x10/Documents/Github/Emperor-Simulator",
  branch: "main",
  assetCount: 186,
  thumbnail: "/demo-assets/backgrounds/audience-hall-day.webp",
};

export const demoAssets: GameAsset[] = [
  {
    id: "portrait-shen-yan",
    key: "portrait.shen-yan.neutral",
    name: "沈渊（文官）· 中立姿态",
    kind: "media",
    category: "2d-media",
    subtype: "角色 / 立绘",
    tags: ["核心人物", "文官", "透明背景"],
    reviewStatus: "pending",
    qaPassed: 4,
    qaTotal: 4,
    updatedAt: "2026-07-19T15:42:18+08:00",
    updatedLabel: "今天 15:42",
    updatedBy: "本机用户",
    thumbnails: [
      portrait("shen-yan", "neutral"),
      portrait("shen-yan", "deliberating"),
      portrait("shen-yan", "remonstrating"),
    ],
    revisions: [
      {
        id: "r03",
        label: "r03（候选）",
        image: portrait("shen-yan", "neutral"),
        createdAt: "2026-07-19 15:42:18",
        author: "本机用户",
        resolution: "1024 × 1536",
        fileSize: "176 KB",
        status: "candidate",
      },
      {
        id: "r02",
        label: "r02（已批准）",
        image: portrait("shen-yan", "deliberating"),
        createdAt: "2026-07-18 22:06:31",
        author: "本机用户",
        resolution: "1024 × 1536",
        fileSize: "164 KB",
        status: "approved",
      },
    ],
    prompt:
      "明代文官肖像，30–45 岁男性，官帽端正，手持笏板，站立，中立表情，写实风格，正面半身，光线柔和，细节清晰。保持沈渊的脸部特征与服饰一致。",
    negativePrompt: "卡通、过度渲染、模糊、变形、低清、文字、水印、多余手指、裁切头部",
    model: "gpt-image-2",
    recipe: "portrait-core-v3",
    seed: "2789445163",
    qa: qa("1024 × 1536", "176 KB"),
  },
  {
    id: "portrait-gu-ting",
    key: "portrait.gu-ting.commanding",
    name: "顾霆（礼部尚书）· 发令",
    kind: "media",
    category: "2d-media",
    subtype: "角色 / 立绘",
    tags: ["核心人物", "朝臣", "表情组"],
    reviewStatus: "pending",
    qaPassed: 4,
    qaTotal: 4,
    updatedAt: "2026-07-19T15:41:02+08:00",
    updatedLabel: "今天 15:41",
    updatedBy: "本机用户",
    thumbnails: [
      portrait("gu-ting", "neutral"),
      portrait("gu-ting", "calculating"),
      portrait("gu-ting", "commanding"),
    ],
    revisions: [
      {
        id: "r04",
        label: "r04（候选）",
        image: portrait("gu-ting", "commanding"),
        createdAt: "2026-07-19 15:41:02",
        author: "本机用户",
        resolution: "1024 × 1536",
        fileSize: "158 KB",
        status: "candidate",
      },
      {
        id: "r03",
        label: "r03（已批准）",
        image: portrait("gu-ting", "neutral"),
        createdAt: "2026-07-18 20:31:54",
        author: "本机用户",
        resolution: "1024 × 1536",
        fileSize: "178 KB",
        status: "approved",
      },
    ],
    prompt: "明代高级文官，暗红官袍，发令姿态，神情果决，与顾霆中立立绘保持身份与面部一致。",
    negativePrompt: "卡通、现代服装、错误官帽、裁切、低清、水印、文字",
    model: "gpt-image-2",
    recipe: "portrait-expression-edit-v3",
    seed: "762031984",
    qa: qa("1024 × 1536", "158 KB"),
  },
  {
    id: "portrait-han-lie",
    key: "portrait.han-lie.resolute",
    name: "韩烈（大将军）· 坚毅",
    kind: "media",
    category: "2d-media",
    subtype: "角色 / 立绘",
    tags: ["核心人物", "武将", "甲胄"],
    reviewStatus: "pending",
    qaPassed: 3,
    qaTotal: 4,
    updatedAt: "2026-07-19T15:40:37+08:00",
    updatedLabel: "今天 15:40",
    updatedBy: "本机用户",
    thumbnails: [
      portrait("han-lie", "neutral"),
      portrait("han-lie", "resolute"),
      portrait("han-lie", "angered"),
    ],
    revisions: [
      {
        id: "r03",
        label: "r03（候选）",
        image: portrait("han-lie", "resolute"),
        createdAt: "2026-07-19 15:40:37",
        author: "本机用户",
        resolution: "1024 × 1536",
        fileSize: "192 KB",
        status: "candidate",
      },
      {
        id: "r02",
        label: "r02（已批准）",
        image: portrait("han-lie", "neutral"),
        createdAt: "2026-07-18 18:14:22",
        author: "本机用户",
        resolution: "1024 × 1536",
        fileSize: "184 KB",
        status: "approved",
      },
    ],
    prompt: "明代大将军半身立绘，玄铁甲胄，坚毅警觉，保留韩烈面部、发冠与甲片结构。",
    negativePrompt: "奇幻盔甲、夸张武器、背景、裁切、低清、文字、水印",
    model: "gpt-image-2",
    recipe: "portrait-expression-edit-v3",
    seed: "152682210",
    qa: [
      ...qa("1024 × 1536", "192 KB").slice(0, 3),
      { id: "alpha", label: "透明边缘与残色检查", result: "右肩需复核", passed: false },
    ],
  },
  {
    id: "artifact-batch",
    key: "icon.artifact.batch-01",
    name: "文物道具图标组",
    kind: "media",
    category: "2d-media",
    subtype: "物品 / 图标",
    tags: ["收藏品", "48px 预览", "透明背景"],
    reviewStatus: "pending",
    qaPassed: 4,
    qaTotal: 4,
    updatedAt: "2026-07-19T15:38:00+08:00",
    updatedLabel: "今天 15:38",
    updatedBy: "本机用户",
    thumbnails: [
      "/demo-assets/icons/artifact-01.webp",
      "/demo-assets/icons/artifact-15.webp",
      "/demo-assets/icons/artifact-42.webp",
    ],
    revisions: [
      {
        id: "r02",
        label: "r02（候选）",
        image: "/demo-assets/icons/artifact-15.webp",
        createdAt: "2026-07-19 15:38:00",
        author: "本机用户",
        resolution: "256 × 256",
        fileSize: "18 KB",
        status: "candidate",
      },
      {
        id: "r01",
        label: "r01（已批准）",
        image: "/demo-assets/icons/artifact-01.webp",
        createdAt: "2026-07-18 17:21:43",
        author: "本机用户",
        resolution: "256 × 256",
        fileSize: "14 KB",
        status: "approved",
      },
    ],
    prompt: "宫廷收藏品图标，正交视角，完整轮廓，适合 48×48 运行时展示，透明背景。",
    negativePrompt: "场景背景、文字、边框、过小主体、低对比度",
    model: "gpt-image-2",
    recipe: "artifact-icon-v2",
    seed: "30191251",
    qa: qa("256 × 256", "18 KB"),
  },
  {
    id: "cg-court",
    key: "cg.court-confrontation",
    name: "朝堂对峙",
    kind: "media",
    category: "2d-media",
    subtype: "2D 媒体 / CG",
    tags: ["主线", "朝堂", "宽银幕"],
    reviewStatus: "approved",
    qaPassed: 5,
    qaTotal: 5,
    updatedAt: "2026-07-19T14:58:00+08:00",
    updatedLabel: "今天 14:58",
    updatedBy: "本机用户",
    thumbnails: ["/demo-assets/cgs/court-confrontation.webp"],
    revisions: [
      {
        id: "r02",
        label: "r02（已批准）",
        image: "/demo-assets/cgs/court-confrontation.webp",
        createdAt: "2026-07-19 14:58:00",
        author: "本机用户",
        resolution: "1536 × 1024",
        fileSize: "228 KB",
        status: "approved",
      },
    ],
    prompt: "明代朝堂对峙场景，群臣分列，皇座居中，烛光与晨光交叠，电影感宽幅构图。",
    negativePrompt: "现代物件、空旷、文字、过曝、模糊人物",
    model: "gpt-image-2",
    recipe: "cg-story-v2",
    seed: "unknown",
    qa: qa("1536 × 1024", "228 KB"),
  },
  {
    id: "cg-palace",
    key: "cg.palace-banquet",
    name: "宫廷夜宴",
    kind: "media",
    category: "2d-media",
    subtype: "2D 媒体 / CG",
    tags: ["宴会", "夜景", "宽银幕"],
    reviewStatus: "approved",
    qaPassed: 5,
    qaTotal: 5,
    updatedAt: "2026-07-19T14:52:00+08:00",
    updatedLabel: "今天 14:52",
    updatedBy: "本机用户",
    thumbnails: ["/demo-assets/cgs/palace-banquet.webp"],
    revisions: [
      {
        id: "r03",
        label: "r03（已批准）",
        image: "/demo-assets/cgs/palace-banquet.webp",
        createdAt: "2026-07-19 14:52:00",
        author: "本机用户",
        resolution: "1536 × 1024",
        fileSize: "268 KB",
        status: "approved",
      },
    ],
    prompt: "宫廷夜宴全景，丝竹、灯笼、群臣席位，叙事性构图，明代写实风格。",
    negativePrompt: "现代灯具、空桌、文字、模糊、畸变",
    model: "gpt-image-2",
    recipe: "cg-story-v2",
    seed: "unknown",
    qa: qa("1536 × 1024", "268 KB"),
  },
  {
    id: "background-batch",
    key: "background.palace.batch-01",
    name: "宫廷场景背景组",
    kind: "media",
    category: "2d-media",
    subtype: "2D 媒体 / 背景",
    tags: ["宫殿", "场景", "环境"],
    reviewStatus: "rejected",
    qaPassed: 3,
    qaTotal: 4,
    updatedAt: "2026-07-19T14:36:00+08:00",
    updatedLabel: "今天 14:36",
    updatedBy: "本机用户",
    thumbnails: [
      "/demo-assets/backgrounds/audience-hall-day.webp",
      "/demo-assets/backgrounds/imperial-study-day.webp",
      "/demo-assets/backgrounds/autumn-hunt.webp",
    ],
    revisions: [
      {
        id: "r03",
        label: "r03（已驳回）",
        image: "/demo-assets/backgrounds/imperial-study-day.webp",
        createdAt: "2026-07-19 14:36:00",
        author: "本机用户",
        resolution: "1536 × 1024",
        fileSize: "311 KB",
        status: "rejected",
      },
      {
        id: "r02",
        label: "r02（已批准）",
        image: "/demo-assets/backgrounds/audience-hall-day.webp",
        createdAt: "2026-07-18 13:08:22",
        author: "本机用户",
        resolution: "1536 × 1024",
        fileSize: "262 KB",
        status: "approved",
      },
    ],
    prompt: "明代宫廷室内背景，无遮挡的玩法舞台区，准确透视，日间自然光，写实绘景。",
    negativePrompt: "正面人物、文字、现代家具、过暗、透视错误",
    model: "gpt-image-2",
    recipe: "background-location-v2",
    seed: "54088213",
    qa: [
      ...qa("1536 × 1024", "311 KB").slice(0, 2),
      { id: "safe-zone", label: "玩法安全区无遮挡", result: "右侧被屏风占用", passed: false },
      ...qa("1536 × 1024", "311 KB").slice(3),
    ],
  },
];

export const demoJob: JobSummary = {
  id: "image-batch-20260719-01",
  name: "图像生成批次 #20260719-01",
  status: "completed",
  progress: 100,
  completed: 24,
  total: 24,
  passed: 22,
  previewImages: [
    "/demo-assets/cgs/court-confrontation.webp",
    portrait("shen-yan", "neutral"),
    portrait("han-lie", "resolute"),
    "/demo-assets/icons/artifact-15.webp",
  ],
  outputPath: "output/game-assets/candidates/20260719-01",
};

export const demoPayload: WorkbenchPayload = {
  project: demoProject,
  assets: demoAssets,
  job: demoJob,
  source: "demo",
};
